services:
  web:
    build: ./project
    command: uv run uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8004:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgres://postgres:postgres@web-db:5432/web_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@web-db:5432/web_test
      # Azure Authentication Configuration
      - TENANT_ID=078c6c18-7434-4931-81cd-7b9603fda5a2
      - APP_CLIENT_ID=ab2eb96c-e97e-422f-a405-adbf8a1c0c66
      - OPENAPI_CLIENT_ID=51791809-45e5-4697-b005-60e05dfccb2b
      - BACKEND_CORS_ORIGINS=["http://localhost:8004"]
      - SCOPE_DESCRIPTION=user_impersonation
    depends_on:
      - web-db

  web-db:
    build:
      context: ./project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
